params:
  seed: 42
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None

  config:
    name: Isaac-Lift-Cube-Franka-PPO
    env_name: rlgpu
    device: cuda
    device_name: cuda
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    clip_value: True
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 250
    save_best_after: 50
    save_frequency: 25
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 64
    minibatch_size: 4096
    mini_epochs: 5
    critic_coef: 2.0
    clip_actions: False
    seq_len: 4
    bounds_loss_coef: 0.0001

  env:
    clip_observations: 5.0
    clip_actions: 1.0
